apiVersion : apps/v1
kind: Deployment
metadata:
  name: testdevspringbootapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdevspringbootapp
  template:
    metadata:
      labels:
        app: testdevspringbootapp 
    spec:
      containers:
        - name: testdevspringbootapp 
          image: ccrinfydev.azurecr.io/testdevspringbootapp
          ports:
          - containerPort: 80
